"""Add financial products and market data tables

Revision ID: 9726155ffbbf
Revises: d3161465fa1b
Create Date: 2026-09-02 16:33:30.492623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9726155ffbbf'
down_revision: Union[str, Sequence[str], None] = 'd3161465fa1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('product_type', sa.Enum('mutual_fund', 'etf', 'stock', 'bond', 'fixed_deposit', 'government_security', 'index_fund', 'gold', 'other', name='product_type_enum'), nullable=False),
    sa.Column('asset_class', sa.Enum('equity', 'debt', 'gold', 'cash', 'hybrid', 'other', name='asset_class_enum'), nullable=False),
    sa.Column('issuer', sa.String(length=255), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('risk_level', sa.Enum('low', 'moderate', 'high', 'very_high', name='product_risk_level_enum'), nullable=False),
    sa.Column('expense_ratio', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('minimum_investment', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_products_asset_class'), 'financial_products', ['asset_class'], unique=False)
    op.create_index(op.f('ix_financial_products_id'), 'financial_products', ['id'], unique=False)
    op.create_index(op.f('ix_financial_products_product_type'), 'financial_products', ['product_type'], unique=False)
    op.create_index(op.f('ix_financial_products_risk_level'), 'financial_products', ['risk_level'], unique=False)
    op.create_index(op.f('ix_financial_products_symbol'), 'financial_products', ['symbol'], unique=True)
    op.create_table('market_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('financial_product_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('high_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('low_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('close_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['financial_product_id'], ['financial_products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('financial_product_id', 'timestamp', name='uq_market_data_product_timestamp')
    )
    op.create_index(op.f('ix_market_data_financial_product_id'), 'market_data', ['financial_product_id'], unique=False)
    op.create_index(op.f('ix_market_data_id'), 'market_data', ['id'], unique=False)
    op.create_index('ix_market_data_product_timestamp', 'market_data', ['financial_product_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_market_data_timestamp'), 'market_data', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_market_data_timestamp'), table_name='market_data')
    op.drop_index('ix_market_data_product_timestamp', table_name='market_data')
    op.drop_index(op.f('ix_market_data_id'), table_name='market_data')
    op.drop_index(op.f('ix_market_data_financial_product_id'), table_name='market_data')
    op.drop_table('market_data')
    op.drop_index(op.f('ix_financial_products_symbol'), table_name='financial_products')
    op.drop_index(op.f('ix_financial_products_risk_level'), table_name='financial_products')
    op.drop_index(op.f('ix_financial_products_product_type'), table_name='financial_products')
    op.drop_index(op.f('ix_financial_products_id'), table_name='financial_products')
    op.drop_index(op.f('ix_financial_products_asset_class'), table_name='financial_products')
    op.drop_table('financial_products')
    # ### end Alembic commands ###
